### ISSUE TITLE
event size mismatch error

### ISSUE THREAD

**Issue by jychoi-hpc** [codes-org/codes#201]
Hi. I am trying to run the following example shown in the CODES Tutorial slide at HOTI 2017 (page 29, http://www.mcs.anl.gov/projects/codes/files/2017/08/codes-hoti-tutorial-v4.pdf)

```
./src/network-workloads/model-net-mpi-replay \
--sync=1 --disable_compute=1 --workload_type="dumpi" --num_net_traces=1728 \
--workload_file=df_AMG_n1728_dumpi/dumpi-2014.03.03.14.55.50- \
-- ../src/network-workloads/conf/dragonfly-custom/modelnet-test-dragonfly-edison.conf
```
but getting the following error:
```
*** START SEQUENTIAL SIMULATION ***

Set num_servers per router 4, servers per injection queue per router 4, servers per node copy queue per node 1, num nics 4
node: 0: error: ../src/networks/model-net/core/model-net.c:322: Error: model_net trying to transmit an event of size 736 but ROSS is configured for events of size 608
```

I am using the master branch for both codes and ross.

I appreciate any help and advice in advance.

**Comment by nmcglohon** [comment]
The event sizes for some models have increased since HOTI. Event sizes are specified in the configuration file given. 

In the configuration file “modelnet-test-dragonfly-edison.conf” change “message size” to “736”

**Comment by jychoi-hpc** [comment]
Great!! It works. Thank you for the quick help.

**Comment by nmcglohon** [comment]
No problem! It’s a quirk of ROSS needing some number of bytes to alloc for event messages but CODES having different sizes of events depending on what model is used.
