### ISSUE TITLE
"Error: failed to find workload generator dumpi-trace-workload"

### ISSUE THREAD

**Issue by lwh1990** [codes-org/codes#207]
Hi, I am trying to run the following example shown below and I am using the master branch for codes and ROSS.

`./model-net-mpi-replay  --sync=1 --disable_compute=1 --workload_type="dumpi"  --num_net_traces=27
--workload_file=df_AMG_n27_dumpi/dumpi-2014.03.03.14.55.00-   -- ./src/network-workloads/conf/modelnet-mpi-test-torus.conf`

But it show some errors:
*********************************************************************************
Fri Aug  7 03:52:27 2020

ROSS Version: HEAD-HASH-NOTFOUND

tw_net_start: Found world size to be 2
NIC num injection port not specified, setting to 1
NIC seq delay not specified, setting to 10.000000
NIC num copy queues not specified, setting to 1
Bandwidth of compute node channels not specified, setting to 20.000000
within node transfer per byte delay is 0.050000
Within-node eager limit (node_eager_limit) not specified, setting to 16000

ROSS Core Configuration:
        Total PEs                                                    2
        Total KPs                                          [Nodes (2) x KPs (16)] 32
        Total LPs                                                   64
        Simulation End Time                                3600000000000.00
        LP-to-PE Mapping                                   model defined

ROSS Event Memory Allocation:
        Model events                                              8193
        Network events                                              16
        Total events                                              8208

Error: failed to find workload generator dumpi-trace-workload
Error: failed to find workload generator dumpi-trace-workload
Error: failed to find workload generator dumpi-trace-workload
Error: failed to find workload generator dumpi-trace-workload
Error: failed to find workload generator dumpi-trace-workload
Error: failed to find workload generator dumpi-trace-workload
Error: failed to find workload generator dumpi-trace-workload
Error: failed to find workload generator dumpi-trace-workload
Error: failed to find workload generator dumpi-trace-workload
Error: failed to find workload generator dumpi-trace-workload
Error: failed to find workload generator dumpi-trace-workload
Error: failed to find workload generator dumpi-trace-workload
Error: failed to find workload generator dumpi-trace-workload
Error: failed to find workload generator dumpi-trace-workload
Error: failed to find workload generator dumpi-trace-workload
Error: failed to find workload generator dumpi-trace-workload
Error: failed to find workload generator dumpi-trace-workload
Error: failed to find workload generator dumpi-trace-workload
Error: failed to find workload generator dumpi-trace-workload
Error: failed to find workload generator dumpi-trace-workload
Error: failed to find workload generator dumpi-trace-workload
Error: failed to find workload generator dumpi-trace-workload
Error: failed to find workload generator dumpi-trace-workload
Error: failed to find workload generator dumpi-trace-workload
Error: failed to find workload generator dumpi-trace-workload
Error: failed to find workload generator dumpi-trace-workload
Error: failed to find workload generator dumpi-trace-workload
*** START PARALLEL OPTIMISTIC SIMULATION WITH SUSPEND LP FEATURE ***

model-net-mpi-replay: src/workload/codes-workload.c:237: codes_workload_get_next: Assertion `tmp' failed.
model-net-mpi-replay: src/workload/codes-workload.c:237: codes_workload_get_next: Assertion `tmp' failed.
[localhost:29913] *** Process received signal ***
[localhost:29912] *** Process received signal ***
[localhost:29913] Signal: Aborted (6)
[localhost:29913] Signal code:  (-6)
[localhost:29912] Signal: Aborted (6)
[localhost:29912] Signal code:  (-6)
[localhost:29913] *** End of error message ***
[localhost:29912] *** End of error message ***
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
************************************************************************************
Thanks for any help.

**Comment by lwh1990** [comment]
The problem solved after I installed the dumpi library. This issue can be closed.

**Comment by nmcglohon** [comment]
Glad you were able to figure it out!

**Comment by ZekangLan** [comment]
Hi lwh1990，
    This problem also occurs in my test. I have installed the dumpi library as you suggested. However i don't know how to link CODES to DUMPI. Could you specify it. Thanks.

**Comment by ZekangLan** [comment]
Hi nmcglohon, 
 Could you specify how to link CODES to DUMPI library.  Thanks

**Comment by ZekangLan** [comment]
The problem occurs when i want to replay application traces on network models as the illustration at https://github.com/codes-org/codes/wiki/codes-dumpi-workload.

**Comment by BingluCS** [comment]
> The problem occurs when i want to replay application traces on network models as the illustration at https://github.com/codes-org/codes/wiki/codes-dumpi-workload.

Hi lzk23
I also confront the same problem. Do you solve it?

**Comment by nmcglohon** [comment]
There's some very old documentation for it somewhere in the wiki if you're using auto tools to build codes. 

I converted codes to CMake a few years ago and there's a DUMPI_BUILD_PATH cmake config that you point to your dumpi installation directory. 

It's been a while since I've worked with CODES though so I don't recall the details thoroughly, unfortunately.

**Comment by BingluCS** [comment]
Thanks, I have found the solution with your help. I used the option --with-dumpi=/path/to/dumpi/install with configure.
