### ISSUE TITLE
FYI ROSS v7.2.1

### ISSUE THREAD

**Issue by gonsie** [codes-org/codes#209]
Ping @nmcglohon there is a new ROSS release on master: v7.2.1. There are no major changes so everything should be good, but let me know if there are issues.

**Comment by nmcglohon** [comment]
Thanks! There will be some updates to CODES being merged in the very near future and will verify that everything works with the latest ROSS.

**Comment by nmcglohon** [comment]
I've made new releases for both CODES and ROSS that confirmed work with each other. Closing.
